// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhw7aKVITVfIxPEA_7l08j-ArDjIIG8TE',
    appId: '1:659833454474:android:cc26cbd4452027de2cd273',
    messagingSenderId: '659833454474',
    projectId: 'gallery-flutter-e6cb6',
    storageBucket: 'gallery-flutter-e6cb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXGh6Y3TKUTC7Ch52a8oZRo4JObF3Fk4U',
    appId: '1:659833454474:ios:e5edbaa1ab54a45d2cd273',
    messagingSenderId: '659833454474',
    projectId: 'gallery-flutter-e6cb6',
    storageBucket: 'gallery-flutter-e6cb6.appspot.com',
    iosClientId: '659833454474-kesvhpeoe2kvadf86rrgrk3r44rs0sgr.apps.googleusercontent.com',
    iosBundleId: 'com.sawrose.gallery-ios',
  );
}
